# Generated by Django 5.0 on 2024-11-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='theme_images/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.theme'),
        ),
    ]
