# Generated by Django 5.0 on 2024-11-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_theme_post_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
